--CREATE DATABASE RACEDAY;

--CREATE TABLE USERS 
--(
--USERID INT IDENTITY (1,1) PRIMARY KEY,
--FULLNAME VARCHAR (50) NOT NULL,
--EMAIL VARCHAR (50) NOT NULL UNIQUE,
--PASSWORDHASH VARCHAR (50) NOT NULL,
--PHONE VARCHAR (50) NOT NULL,
--ROLE VARCHAR (50) NOT NULL
--   CONSTRAINT CK_USER_ROLE
--   CHECK(ROLE  IN ('ORGANISER', 'PARTICIPANT')),
--CREATEDAT DATETIME NOT NULL
-- DEFAULT GETDATE());

--CREATE TABLE EVENTS
--(
--    EVENTSID INT IDENTITY(1,1) PRIMARY KEY,
--    EVENTNAME VARCHAR(50) NOT NULL,
--    DESCRIPTION VARCHAR(50) NOT NULL,
--    EVENTDATE DATE NOT NULL,
--    LOCATION VARCHAR(50) NOT NULL,
--    CAPACITY INT NOT NULL,

--    CONSTRAINT CK_EVENTS_CAPACITY
--        CHECK (CAPACITY > 0),

--    STATUS VARCHAR(50) NOT NULL
--        DEFAULT 'UPCOMING',

--    CONSTRAINT CK_EVENTS_STATUS
--        CHECK (STATUS IN
--        ('UPCOMING', 'OPEN', 'CLOSED', 'COMPLETED', 'CANCELLED'))
--);

CREATE TABLE CATEGORIES
(
  CATEGORYID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  CATEGORYNAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(50) NULL,
);

CREATE TABLE EVENTCATEGORIES
(
  EVENTCATEGORYID INT INDENTITY(1,1) PRIMARY KEY,
  EVENTID INT NOT NULL,
  CATEGORYID INT NOT NULL,
  CONSTRAINT FK_CATEGORIES_EVENT
  FOREIGN KEY (EVENTID)
  REFERENCES  EVENTS(EVENTID),

  CONSTRAINT FK_EVENTCATEGORIES_EVENT
  FOREIGN KEY (CATEGORYID)
  


