--CREATE DATABASE RACEDAY;

--IF OBJECT_ID('dbo. RESULTS','U') IS NOT NULL
--DROP TABLE dbo. RESULTS;

--IF OBJECT_ID('dbo. ENROLMENTS','U') IS NOT NULL
--DROP TABLE dbo. ENROLMENTS;

--IF OBJECT_ID('dbo. EVENTCATEGORIES', 'U') IS NOT NULL
--DROP TABLE dbo. EVENTCATEGORIES;

--IF OBJECT_ID('dbo. CATEGORIES', 'U') IS NOT NULL
--DROP TABLE dbo. CATEGORIES;

--IF OBJECT_ID ('dbo. EVENTS', 'U') IS NOT NULL
--DROP TABLE dbo. EVENTS;

--IF OBJECT_ID(' dbo.USERS', 'U') IS NOT NULL
--DROP TABLE dbo. USERS;

--CREATE TABLE USERS 
--(
--USERID INT IDENTITY (1,1) PRIMARY KEY,
--FULLNAME VARCHAR (50) NOT NULL,
--EMAIL VARCHAR (50) NOT NULL UNIQUE,
--PASSWORDHASH VARCHAR (50) NOT NULL,
--PHONE VARCHAR (50) NOT NULL,
--ROLE VARCHAR (500) NOT NULL
--   CONSTRAINT CK_USER_ROLE
--   CHECK(ROLE  IN ('ORGANISER', 'PARTICIPANT')),
--CREATEDAT DATETIME NOT NULL
-- DEFAULT GETDATE());

--CREATE TABLE EVENTS
--(
--    EVENTID INT IDENTITY(1,1) PRIMARY KEY,
--    EVENTNAME VARCHAR(50) NOT NULL,
--    DESCRIPTION VARCHAR(50) NOT NULL,
--    EVENTDATE DATE NOT NULL,
--    LOCATION VARCHAR(50) NOT NULL,
--    CAPACITY INT NOT NULL,

--    CONSTRAINT CK_EVENTS_CAPACITY
--        CHECK (CAPACITY > 0),

--    STATUS VARCHAR(50) NOT NULL
--        DEFAULT 'UPCOMING',

--    CONSTRAINT CK_EVENTS_STATUS
--        CHECK (STATUS IN
--        ('UPCOMING', 'OPEN', 'CLOSED', 'COMPLETED', 'CANCELLED')),

         -        ORGANISERID INT NOT NULL,

--    CREATEDAt DATETIME NOT NULL
--        DEFAULT GETDATE(),

--    CONSTRAINT FK_EVENT_ORGANISER
--        FOREIGN KEY (ORGANISERID)
--        REFERENCES USERS(USERID)
--);

--CREATE TABLE CATEGORIES
--(
--  CATEGORYID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--  CATEGORYNAME VARCHAR(50) NOT NULL,
--  DESCRIPTION VARCHAR(50) NULL,

--  MINIMUMAGE INT NULL
--     CONSTRAINT CK_CATEGOTY_MINIMUMAGE
--     CHECK (MINIMUMAGE IS NULL OR MINIMUMAGE >= 0),
-- MAXIMUMAGE INT NULL
-- CONSTRAINT CK_CATEGOTY_MAXIIMUMAGE
--     CHECK (MAXIMUMAGE IS NULL OR MAXIMUMAGE >= 0)
--

CREATE TABLE EVENTCATEGORIES
(
  EVENTCATEGORYID INT IDENTITY(1,1) PRIMARY KEY,
  EVENTSID INT NOT NULL,
  CATEGORYID INT NOT NULL,
  
  CONSTRAINT FK_EVENTCATEGORIES_EVENT
  FOREIGN KEY (EVENTSID)
  REFERENCES  EVENTS(EVENTSID),

CONSTRAINT FK_EVENTCATEGORIES_CATEGORY
  FOREIGN KEY (CATEGORYID)
  REFERENCES CATEGORIES(CATEGORYID),
  
CONSTRAINT UQ_EVENTCATEGORIES
  UNIQUE (EVENTID, CATEGORYID)
  );

CREATE TABLE ENROLMENTS
(
  ENROLMENTID INT IDENTITY(1,1)PRIMARY KEY,
  USERID INT NOT NULL,
  EVENTID INT NOT NULL,
  CATEGORYID INT NOT NULL,
  ENROLMENTDATE DATETIME NOT NULL
      DEFAULT GETDATE(),

  STATUS VARCHAR(50) NOT NULL
      DEFAULT 'ACTIVE'
      CONSTRAINT CK_ENROLMENT_STATUS
      CHECK (STATUS IN ('ACTIVE', 'CANCELLED', 'COMPLETED')),

  CONSTRAINT FK_ENROLMENTS_USER
      FOREIGN KEY (USERID)
      REFERENCES USERS(USERID),

  CONSTRAINT FK_ENROLMENTS_EVENT
       FOREIGN KEY (EVENTID)
       REFERENCES EVENTS(EVENTSID),

  CONSTRAINT FK_ENROLMENTS_CATEGORY
       FOREIGN KEY (CATEGORYID)
       REFERENCES CATEGORIES(CATEGORYID),

  CONSTRAINT UQ_EVENT
     UNIQUE (USERID,EVENTID)
  );

CREATE TABLE RESULTS 
(
  RESULTID INT IDENTITY (1,1) PRIMARY KEY, 
  ENROLMENTID INT NOT NULL UNIQUE,
  POSITION INT NOT NULL
     CONSTRAINT CK_RESULTS_POSITION
     CHECK (POSITION > 0),

  FINISHTIME TIME NOT NULL,

  RESULTSTATUS VARCHAR(50) NOT NULL
  DEFAULT 'FINISHED'
  CONSTRAINT CK_RESULTS_STATUS
  CHECK (RESULTSTATUS IN ('FINISHIED', 'DNF','DNS')),

  RECORDEDAT DATETIME NOT NULL
     DEFAULT GETDATE(),

  CONSTRAINT FK_RESULTS_ENROLMENT
     FOREIGN KEY (ENROLMENTID)
    REFERENCES ENROLMENTS(ENROLMENTID)
  );

INSERT INTO USERS
(
  FULLNAME,
  EMAIL,
  PASSWORDHASH,
  PHONE,
  ROLE
  )
VALUES
(
 'LEBOHANG MOKHALEHA',
 'THEBOYMLK@CO.ZA',
 'HASHED_PASSWORD_001',
 '0768910692',
 'ORGANISER'
),
(
  'CHARLES MALATJI',
  'MRMALATJIESIR@CO.ZA',
  'HASHED_PASSWORD_002',
  '0839632460',
  'ORGANISER'
 ),
 (
  'HLELO MALULEKA',
  'MYBRADAR@CO.ZA',
  'HASHED_PASSWORD_003',
  '0835042434',
  'PARTICIPANT'
 ),
 (
  'LETHABO MOKGOTSI',
  'THEOILY@CO.ZA',
  'HASHED_PASSEDWORD-004',
  '0795830258',
  'PARTICIPANT'
  );
 --INSERT INTO EVENTS
--(
--  EVENTNAME,
--  DESCRIPTION,
--  EVENTDATE,
--  LOCATION,
--  CAPACITY,
--  STATUS,
--  ORGANISERID
--)
--VALUES
--(
--  'JOHANNESBURG CITY RUN',
--  'A COMMUNITY ROADRUNNING EVENT IN JOHANNESBURG.',
--  '2026-10-10',
--  'JOHANNESBURG',
--  500,
--  'OPEN',
--  1
--),
--(
--  'PRETORIA SPRING MARATHON',
--  'A COMPTITITVE MARATHON EVENT HELD IN PRETORIA.',
--  '2026-10-24',
--  'PRETORIA',
--  1000,
--  'UPCOMING',
--  1
--),
--(
--  'LIMPOPO FUN RUN',
--  'A FAMILY-FRIEND RUNNING EVENT IN LIMPOPO',
--  '2026-11-07',
--  'POLOKWANE',
--  300,
--  'UPCOMING',
--  1
--);
  
 INSERT INTO Categories
(
CategoryName, 
Description, 
MinimumAge, 
MaximumAge
)
VALUES
(
' 5 KM',
"Five kilometre fun run.',
10, 
NULL
),
(
'10 KM',
"Ten kilometre road race.',
14,
NULL
),
(
'21 KM',
'Half marathon category.',
16,
NULL
),
(
'42 KM',
'Full marathon category.',
18, 
NULL
);
  


  


